name: Go

on:
  push:
  pull_request:


jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [1.11, 1.12, 1.13, tip]
        os: [ubuntu-latest, windows-latest]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go vet ./...

    - name: Test
      run: go test -v ./...
